FROM balenalib/raspberry-pi-python:latest

RUN install_packages \
    libusb-1.0-0-dev \ 
    libpcsclite-dev \  
    pcscd \ 
    pcsc-tools \ 
    libacsccid1 \ 
    wireless-tools \
    python-setuptools \
    swig \
    gcc \
    python-dev

# Upgrade pip
RUN pip install --upgrade pip

# Install pyscard library
RUN pip install pyscard

# Copy everything into the container
COPY . ./

# Start application
CMD ["bash", "start.sh"]
