FROM balenalib/raspberry-pi-python:latest
ENV UDEV=on

RUN install_packages \
    libusb-1.0-0-dev \ 
    libpcsclite-dev \
    uhubctl \
    pcscd \ 
    pcsc-tools \ 
    libacsccid1 \ 
    wireless-tools \
    python-setuptools \
    swig \
    gcc \
    python-dev 

# Upgrade pip

RUN pip install --upgrade pip
RUN pip install pyscard


# Copy everything into the container
COPY . ./

# Start application
CMD ["bash", "start.sh"]
